### ISSUE TITLE
localhost connection

### ISSUE THREAD

**Issue by therealOri** [ultrasecurity/DarkSide#1]
I am unable to connect to the localhost php site.

# This is the message I get no matter what I do.

```
Unable to connect.

Firefox can’t establish a connection to the server at localhost.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

# Same thing on google chrome.

**Comment by Boanerge02** [comment]
Hay errores en la instalacion de pip install zipfile

**Comment by harshalgithub** [comment]
Not able to run "Social Engineering" functions, getting below error in log.log

[Fri Dec 18 03:17:18 2020] [::1]:8880 [200]: /Template/assets/images/brand/icon.png
ERROR: The process "ngrok*" not found.
ERROR: The process "16028" not found.
Traceback (most recent call last):
  File "ngrok.py", line 102, in <module>
    phpserv()
  File "ngrok.py", line 30, in phpserv
    getpid()
  File "ngrok.py", line 50, in getpid
    pid = [item.split()[1] for item in os.popen('tasklist').read().splitlines()[4:] if "php.exe" in item.split()]
  File "C:\Program Files\Python38\lib\os.py", line 981, in popen
    proc = subprocess.Popen(cmd,
  File "C:\Program Files\Python38\lib\subprocess.py", line 804, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Program Files\Python38\lib\subprocess.py", line 1157, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Program Files\Python38\lib\subprocess.py", line 1204, in _make_inheritable
    h = _winapi.DuplicateHandle(
OSError: [WinError 6] The handle is invalid

**Comment by Stavros3** [comment]
> Hay errores en la instalacion de pip install zipfile

on the requirments file, change zipfile to zipfile36
