### ISSUE TITLE
DarkSide

### ISSUE THREAD

**Issue by teslaelon9** [ultrasecurity/DarkSide#10]
Traceback (most recent call last):
  File "run.py", line 86, in <module>
    banner()
  File "run.py", line 20, in banner
    subprocess.Popen('neofetch')
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

**Comment by poobum653** [comment]
To resolve this edit install.sh

Remove the line: 
apt-get neofetch

Add the lines:
add-apt-repository ppa:dawidd0811/neofetch
apt-get update
apt-get install neofetch

**Comment by N0rdicSec** [comment]
I got the issue mentioned. So, performed you tip.

Did run `bash install.sh` and then `python3 run.py`. Finally, all works well!

>
