### ISSUE TITLE
Php issur

### ISSUE THREAD

**Issue by Chomikmarkus** [ultrasecurity/DarkSide#13]
Some php issue: 
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
 
Traceback (most recent call last):
  File "run.py", line 87, in <module>
    phpserv()
  File "run.py", line 51, in phpserv
    subprocess.Popen(('php', '-S', 'localhost:'+port,'-t','T
emplate'), stdout=phplog, stderr=phplog)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __in
it__
    self._execute_child(args, executable, preexec_fn, close_
fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _ex
ecute_child
    raise child_exception_type(errno_num, err_msg, err_filen
ame)
FileNotFoundError: [Errno 2] No such file or directory: 'php
'
root@vps158041:/opt/DarkSide#
![Screenshot_20211019-232346](https://user-images.githubusercontent.com/92059377/137984971-13e6d7fe-fcc2-441a-a97b-60246b946e9a.png)

**Comment by Sajibekanti** [comment]
sudo apt-get install php 
it will fix PHP issue

**Comment by kait0kid** [comment]
Besides to run : 

 sudo apt-get install php 

you will need to run:

sudo apt-get install neofetch
